name: dbt CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    name: Run dbt models and tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/260309254227/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "dbt-github-actions@nyc-taxi-lakehouse-497608.iam.gserviceaccount.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << 'EOF'
          nyc_taxi:
            outputs:
              dev:
                type: bigquery
                method: oauth
                project: nyc-taxi-lakehouse-497608
                dataset: nyc_taxi
                threads: 4
                timeout_seconds: 300
                location: asia-southeast1
            target: dev
          EOF

      - name: Run dbt
        working-directory: ./nyc_taxi
        run: |
          dbt deps
          dbt run
          dbt test

      - name: Upload dbt logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-logs
          path: nyc_taxi/logs/